{"name": "test_not_authorized_no_session_token", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "def test_not_authorized_no_session_token():\n        org = orgs_tbl.insert()\n        user = endusers_tbl.insert(org_id=org.Id.value)\n        endusers_tbl.insert_session(user_id=user.Id.value)\n>       GetAuth().request().verify()\n\ntests/enduser/test_auth.py:17: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nqa/api/enduser/calls.py:20: in verify\n    self.verify_response(resp_body=resp_body)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <qa.api.enduser.calls.GetAuth object at 0x1040105e0>, error_code = None, resp_body = {'anonymous': True}\nignore_order = False, exclude_paths = None, normalize = False\n\n    def verify_response(self, error_code=None, resp_body=None,\n                        ignore_order=False, exclude_paths=None,\n                        normalize=False):\n        if error_code:\n            assert self.response.status_code == error_code, (\n                f'Unexpected code: {self.response.status_code}'\n            )\n        else:\n>           assert self.response.status_code == 200\nE           AssertionError\n\nqa/tools/caller.py:87: AssertionError"}, "start": 1648640655136, "stop": 1648640655586, "uuid": "5c4af678-af2b-4c86-8f83-eeea6cf353df", "historyId": "5a6d99b481e7582848e3297782a2cc3e", "testCaseId": "1cec6078275acdf0d123b1cac382f77b", "fullName": "tests.enduser.test_auth#test_not_authorized_no_session_token", "labels": [{"name": "parentSuite", "value": "tests.enduser"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Elenas-MacBook-Pro.local"}, {"name": "thread", "value": "59719-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.enduser.test_auth"}]}