{"name": "test_not_authorized_no_token", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "def test_not_authorized_no_token():\n>       GetAuth().request().verify()\n\ntests/enduser/test_auth.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nqa/api/enduser/calls.py:20: in verify\n    self.verify_response(resp_body=resp_body)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <qa.api.enduser.calls.GetAuth object at 0x103ff6520>, error_code = None, resp_body = {'anonymous': True}\nignore_order = False, exclude_paths = None, normalize = False\n\n    def verify_response(self, error_code=None, resp_body=None,\n                        ignore_order=False, exclude_paths=None,\n                        normalize=False):\n        if error_code:\n            assert self.response.status_code == error_code, (\n                f'Unexpected code: {self.response.status_code}'\n            )\n        else:\n>           assert self.response.status_code == 200\nE           AssertionError\n\nqa/tools/caller.py:87: AssertionError"}, "start": 1648640654636, "stop": 1648640655091, "uuid": "66d6053d-541d-47e0-8413-2a78df0f1910", "historyId": "34e8cc715f69588704c60597d8ecd7fc", "testCaseId": "b1719b3b17c9e101ad1282374b6e9dc7", "fullName": "tests.enduser.test_auth#test_not_authorized_no_token", "labels": [{"name": "parentSuite", "value": "tests.enduser"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Elenas-MacBook-Pro.local"}, {"name": "thread", "value": "59719-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.enduser.test_auth"}]}