{"name": "test_not_authorized_invalid_token", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "def test_not_authorized_invalid_token():\n>       GetAuth(session_token=generate_string()).request().verify()\n\ntests/enduser/test_auth.py:21: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nqa/api/enduser/calls.py:20: in verify\n    self.verify_response(resp_body=resp_body)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <qa.api.enduser.calls.GetAuth object at 0x104223430>, error_code = None, resp_body = {'anonymous': True}\nignore_order = False, exclude_paths = None, normalize = False\n\n    def verify_response(self, error_code=None, resp_body=None,\n                        ignore_order=False, exclude_paths=None,\n                        normalize=False):\n        if error_code:\n            assert self.response.status_code == error_code, (\n                f'Unexpected code: {self.response.status_code}'\n            )\n        else:\n>           assert self.response.status_code == 200\nE           AssertionError\n\nqa/tools/caller.py:87: AssertionError"}, "start": 1648640655594, "stop": 1648640656002, "uuid": "6febb9f0-e8b9-448a-aa41-608a04e7998e", "historyId": "e114a8e6a4e906a5025cc4f938147049", "testCaseId": "6efa4f1fa7f89d0729115e51d6c589fb", "fullName": "tests.enduser.test_auth#test_not_authorized_invalid_token", "labels": [{"name": "parentSuite", "value": "tests.enduser"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "Elenas-MacBook-Pro.local"}, {"name": "thread", "value": "59719-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.enduser.test_auth"}]}